#!/bin/sh

java -cp ./dependency/:target/classes/ -Djava.security.policy=client.policy pl.edu.mimuw.cloudatlas.fetcher.Fetcher &
java -cp ./dependency/:target/classes/ -Djava.security.policy=client.policy pl.edu.mimuw.cloudatlas.cloudatlasClient.Client &
java -cp ./dependency/:target/classes/ -Djava.rmi.server.hostname=localhost -Djava.security.policy=server.policy pl.edu.mimuw.cloudatlas.cloudatlasServer.Server &
java -cp ./dependency/:target/classes/ pl.edu.mimuw.cloudatlas.modules.security.QuerySigner &